[package]
name = "kissbot-channel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
bytes = "1.11"
dashmap = { version = "6.1", features = ["serde"] }
futures = "0.3"
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
async-trait = "0.1"
tracing = "0.1"
kai-ws = { path = "../kai-rs/kai-ws" }
kissbot-api = { path = "../kissbot-api" }
kissbot-security = { path = "../kissbot-security" }
