[package]
name = "kissbot-security"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive","rc"] }
serde_json = "1.0"
thiserror = "2.0"
axum = { version = "0.7", features = ["macros"] }
tower = "0.5"
http = "1"
kai-ws = { path = "../kai-rs/kai-ws" }
kissbot-config = { path = "../kissbot-config" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
